#!/usr/bin/env node
/**
 * Mutation check for the safety-critical rules.
 *
 * A passing test suite proves nothing on its own: a test can pass because the
 * code is right, or because the test never reaches the code. One of ours did
 * exactly that — it set needsHuman true, which routes to hold-for-human, so it
 * never touched the branch it claimed to cover.
 *
 * This breaks each rule on purpose and demands that some test notice. A
 * SURVIVED line means the rule in question is currently unguarded.
 *
 *   node scripts/mutation-check.mjs            # all mutations
 *   node scripts/mutation-check.mjs rate       # only ids containing "rate"
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

/**
 * Each mutation states the rule it breaks, so a SURVIVED line reads as a
 * sentence about the product rather than a diff.
 */
const MUTATIONS = [
  {
    id: "limiter/daily-invite-cap",
    rule: "An account past its daily invite cap must not send",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (usage.invitesToday >= dailyInviteCap(usage.firstActionAt, now)) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "limiter/weekly-ceiling",
    rule: "The weekly invitation ceiling is absolute",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (usage.invitesThisWeek >= LINKEDIN_LIMITS.invitesPerWeek) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "limiter/working-hours",
    rule: "Nothing sends outside the rep's working hours",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (!isWithinWorkingHours(now, usage.workingHours, usage.timezone)) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "limiter/min-gap",
    rule: "Two actions never happen back to back",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (elapsed < LINKEDIN_LIMITS.minGapMs) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "limiter/warmup-ramp",
    rule: "A new account starts at the low cap and ramps",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (days >= warmupDays) return invitesPerDayMax;",
    to: "return invitesPerDayMax;",
    pkg: "@le/linkedin",
  },
  {
    id: "gate/approval-mode",
    rule: "Approval mode holds every reply",
    file: "packages/agents/src/reply.ts",
    from: 'if (rules.mode === "approval") {',
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "gate/pricing",
    rule: "A pricing question always reaches a human",
    file: "packages/agents/src/reply.ts",
    from: "if (rules.handOffOnPricing && classification.mentionsPricing) {",
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "gate/legal",
    rule: "A legal or security question always reaches a human",
    file: "packages/agents/src/reply.ts",
    from: "if (rules.handOffOnLegal && classification.mentionsLegalOrCompliance) {",
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "gate/low-confidence",
    rule: "An unconfident classification reaches a human",
    file: "packages/agents/src/reply.ts",
    from: "if (classification.confidence < rules.minConfidence) {",
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "gate/opt-out",
    rule: "An opt-out stops the sequence, whatever else is true",
    file: "packages/agents/src/reply.ts",
    from: "if (classification.optOut) {",
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "optout/phrase-matching",
    rule: "Opt-out phrases are caught deterministically, not only by the model",
    file: "packages/agents/src/reply.ts",
    from: "return OPT_OUT_PHRASES.some((phrase) => normalized.includes(phrase));",
    to: "return false;",
    pkg: "@le/agents",
  },
  {
    id: "slots/working-hours",
    rule: "No slot is offered outside working hours",
    file: "packages/calendar/src/slots.ts",
    // Both bounds must go: for a 30-minute slot either check alone still
    // constrains the other, so mutating one is a no-op that proves nothing.
    from:
      "      isWithinWorkingHours(start, workingHours, timezone) &&\n" +
      "      isWithinWorkingHours(new Date(end.getTime() - 60_000), workingHours, timezone) &&",
    to: "      true &&",
    pkg: "@le/calendar",
  },
  {
    id: "slots/conflicts",
    rule: "No slot is offered over an existing meeting",
    file: "packages/calendar/src/slots.ts",
    from: "!overlapsAny(cursor, cursor + durationMs, blocks)",
    to: "true",
    pkg: "@le/calendar",
  },
  {
    id: "slots/min-notice",
    rule: "Nothing is offered sooner than the minimum notice",
    file: "packages/calendar/src/slots.ts",
    from: "const earliest = new Date(Math.max(from.getTime(), Date.now() + minNoticeHours * 3_600_000));",
    to: "const earliest = new Date(from.getTime());",
    pkg: "@le/calendar",
  },
  {
    id: "booking/negation",
    rule: "A declined slot is never booked",
    file: "apps/worker/src/jobs/booking.ts",
    from: "if (NEGATION.test(text)) return false;",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "booking/unoffered-slot",
    rule: "Only a slot we actually offered can be booked",
    file: "apps/worker/src/jobs/booking.ts",
    from: "  if (!chosen) return null;",
    to: "  const _unused = chosen;",
    pkg: "@le/worker",
  },
  {
    id: "booking/ambiguity",
    rule: "An ambiguous acceptance books nothing",
    file: "apps/worker/src/jobs/booking.ts",
    from: "if (ordinalMatches.length > 1) return null;",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "invite/personalised-note-is-sent",
    rule: "The note written for a person is the note they receive",
    file: "apps/worker/src/jobs/linkedin-action.ts",
    from: "  const note = personalized?.trim();\n  if (note) return note;",
    to: "  const note = personalized?.trim();\n  if (false && note) return note;",
    pkg: "@le/worker",
  },
  {
    id: "invite/note-matched-by-id",
    rule: "A note reaches the prospect it was written about",
    file: "apps/worker/src/jobs/targeting.ts",
    from: 'const note = notes.get(providerIdByProspectId.get(p.id) ?? "");',
    to: "const note = [...notes.values()][insertedProspects.indexOf(p)];",
    pkg: "@le/worker",
  },
  {
    id: "targeting/only-verifiable-people-are-queued",
    rule: "Nobody enters a campaign whose profile cannot be opened; an invitation is capped, carries restriction risk, and a reviewer must be able to see who they are approving",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "    if (isPublicProfileUrl(candidate.linkedinUrl, candidate.providerId)) {\n      verified.push(candidate);\n      continue;\n    }",
    to: "    verified.push(candidate);\n    continue;",
    pkg: "@le/worker",
  },
  {
    id: "targeting/a-hidden-profile-is-resolved-first",
    rule: "A hidden profile is resolved through the provider before being discarded; the profile endpoint usually knows the address the search omitted",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "      if (isPublicProfileUrl(profile.linkedinUrl, candidate.providerId)) {",
    to: "      if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "targeting/queued-is-visible",
    rule: "Queueing the Targeting Agent is recorded, so a job that never reached the worker is not the same blank screen as one that died in it",
    file: "apps/worker/src/server.ts",
    from: '        name: "targeting.queued",',
    to: '        name: "targeting.ignored",',
    pkg: "@le/worker",
  },
  {
    id: "targeting/a-throw-still-says-why",
    rule: "A job that throws records why before giving up; a throw is not an exit that says anything",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "        reason: `The Targeting Agent hit an error: ${reason}`,",
    to: "        reason: null,",
    pkg: "@le/worker",
  },
  {
    id: "targeting/a-report-names-its-build",
    rule: "Every stopped report stamps the build that produced it; a report that cannot be placed against a deploy costs a deploy to interpret",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "    payload: { reason, build: TARGETING_BUILD, campaignId: job.campaignId ?? null, ...detail },",
    to: "    payload: { reason, campaignId: job.campaignId ?? null, ...detail },",
    pkg: "@le/worker",
  },
  {
    id: "targeting/an-empty-search-is-probed",
    rule: "A search that reached the provider and matched nobody carries the probe that says which filters the provider honours",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "      page.items.length === 0 ? await probeProvider(ctx, account.provider_account_id) : undefined;",
    to: "      undefined;",
    pkg: "@le/worker",
  },
  {
    id: "targeting/says-why-it-stopped",
    rule: "A prospect search that finds nobody says why, instead of looking like a button that did nothing",
    file: "apps/worker/src/jobs/targeting.ts",
    from: '  await recordEvent(ctx.db, {\n    workspaceId: job.workspaceId,\n    name: "targeting.stopped",',
    to: '  if (false) await recordEvent(ctx.db, {\n    workspaceId: job.workspaceId,\n    name: "targeting.stopped",',
    pkg: "@le/worker",
  },
  {
    id: "connect/binds-only-the-caller",
    rule: "Confirming a connection binds the asking rep's account and nobody else's",
    file: "apps/worker/src/server.ts",
    from: "const mine = accounts.filter((a) => a.reference === parsed.data.userId);",
    to: "const mine = accounts;",
    pkg: "@le/worker",
  },
  {
    id: "webhook/signature",
    rule: "An unsigned or wrongly signed webhook is rejected",
    file: "packages/linkedin/src/unipile.ts",
    from: "if (!input.signature || !verifySignature(input.body, input.signature, this.webhookSecret)) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "webhook/fails-closed",
    rule: "A missing webhook secret rejects rather than accepts",
    file: "packages/linkedin/src/unipile.ts",
    from: "if (!this.webhookSecret) {",
    to: "if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "api/bearer-check",
    rule: "The internal API rejects a wrong secret",
    file: "apps/worker/src/server.ts",
    from: "if (!constantTimeEquals(presented, secret)) return c.json({ error: \"unauthorized\" }, 401);",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "api/fails-closed",
    rule: "An unconfigured internal API rejects rather than opens",
    file: "apps/worker/src/server.ts",
    from: 'if (!secret) return c.json({ error: "worker is not configured for internal calls" }, 503);',
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "api/membership",
    rule: "Credentials cannot be bound to a workspace you are not in",
    file: "apps/worker/src/server.ts",
    from: "  return Boolean(data);",
    to: "  return true;",
    pkg: "@le/worker",
  },
  {
    id: "pipeline/do-not-contact",
    rule: "A do-not-contact prospect is never messaged",
    file: "apps/worker/src/jobs/linkedin-action.ts",
    from: "if (prospect.do_not_contact) {",
    to: "if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "pipeline/approved-reply-limiter",
    rule: "An approved reply still passes the rate limiter",
    file: "apps/worker/src/jobs/linkedin-action.ts",
    from: "if (!replyDecision.allowed) {",
    to: "if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "pipeline/reply-stops-sequence",
    rule: "A reply stops the scheduled follow-ups",
    file: "apps/worker/src/jobs/inbound.ts",
    from: 'if (canTransition(cp.status as CampaignProspectStatus, "replied")) {',
    to: "if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "pipeline/webhook-idempotency",
    rule: "A redelivered webhook is not answered twice",
    file: "apps/worker/src/jobs/inbound.ts",
    from: "if (existing) return;",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "billing/trial-expiry",
    rule: "An expired trial stops outreach",
    file: "apps/worker/src/jobs/campaign-tick.ts",
    from: "if (!entitled.get(campaign.workspace_id)) continue;",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "billing/canceled-subscription",
    rule: "A canceled subscription stops sending",
    file: "packages/billing/src/entitlement.ts",
    from: 'if (billing.subscriptionStatus === "canceled" || billing.subscriptionStatus === "unpaid") {',
    to: "if (false) {",
    pkg: "@le/billing",
  },
  {
    id: "billing/read-never-blocked",
    rule: "Reading is never blocked, whatever the billing state",
    file: "packages/billing/src/entitlement.ts",
    from: 'return { canSend: false, canRead: true, reason: "trial_expired", trialDaysLeft: 0 };',
    to: 'return { canSend: false, canRead: false, reason: "trial_expired", trialDaysLeft: 0 };',
    pkg: "@le/billing",
  },
  {
    id: "invites/email-binding",
    rule: "An invitation only admits the address it was sent to",
    file: "apps/web/src/lib/invitations.ts",
    from: "if (invite.email.trim().toLowerCase() !== userEmail.trim().toLowerCase()) {",
    to: "if (false) {",
    pkg: "@le/web",
  },
  {
    id: "invites/expiry",
    rule: "An expired invitation is refused",
    file: "apps/web/src/lib/invitations.ts",
    from: 'if (Date.parse(invite.expires_at) <= now.getTime()) return { ok: false, reason: "expired" };',
    to: "",
    pkg: "@le/web",
  },
  {
    id: "invites/revocation",
    rule: "A revoked invitation stays revoked",
    file: "apps/web/src/lib/invitations.ts",
    from: 'if (invite.revoked_at) return { ok: false, reason: "revoked" };',
    to: "",
    pkg: "@le/web",
  },
  {
    id: "crypto/auth-tag",
    rule: "Tampered ciphertext is rejected",
    file: "apps/worker/src/crypto.ts",
    from: "decipher.setAuthTag(Buffer.from(tagPart, \"base64url\"));",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "retention/live-activity",
    rule: "Retention spares a prospect with an open campaign or upcoming meeting",
    file: "apps/worker/src/jobs/retention.ts",
    from: "if (await hasLiveActivity(db, workspace.id, prospect.id, now)) continue;",
    to: "",
    pkg: "@le/worker",
  },
  {
    id: "retention/tombstone",
    rule: "Erasure leaves a do-not-contact tombstone",
    file: "apps/worker/src/jobs/retention.ts",
    from: "      do_not_contact: true,\n      do_not_contact_reason: `erased: ${input.reason}`,",
    to: "      do_not_contact: false,\n      do_not_contact_reason: null,",
    pkg: "@le/worker",
  },
  {
    id: "targeting/cross-rep-dedupe",
    rule: "A prospect another rep already has is never targeted again",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "const unknown = page.items.filter((c) => !known.has(normalizeLinkedInUrl(c.linkedinUrl)));",
    to: "const unknown = page.items;",
    pkg: "@le/worker",
  },
  {
    id: "targeting/fit-threshold",
    rule: "Nobody below the fit threshold is queued for outreach",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "const shortlist = ranked.filter((r) => !r.disqualified && r.fitScore >= MIN_FIT_TO_QUEUE);",
    to: "const shortlist = ranked;",
    pkg: "@le/worker",
  },
  {
    id: "targeting/draft-not-running",
    rule: "A generated campaign waits for a human before it sends",
    file: "apps/worker/src/jobs/targeting.ts",
    from: '      status: "draft",',
    to: '      status: "running",',
    pkg: "@le/worker",
  },
  {
    id: "targeting/do-not-pursue",
    rule: "A profile marked do-not-pursue produces no campaign",
    file: "apps/worker/src/jobs/targeting.ts",
    from: '    return giveUp(ctx, job, "That customer profile is marked do-not-pursue.");',
    to: "    /* mutated */",
    pkg: "@le/worker",
  },
  {
    id: "targeting/paused-account",
    rule: "No campaign is built on a paused or restricted account",
    file: "apps/worker/src/jobs/targeting.ts",
    from: 'if (!account?.provider_account_id || account.status !== "active") {',
    to: "if (!account?.provider_account_id) {",
    pkg: "@le/worker",
  },
  {
    id: "targeting/canonical-url",
    rule: "Prospects are stored canonically so later runs dedupe against them",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "linkedin_url: normalizeLinkedInUrl(r.candidate.linkedinUrl),",
    to: "linkedin_url: r.candidate.linkedinUrl,",
    pkg: "@le/worker",
  },
  {
    id: "health/the-worker-says-it-started",
    rule: "The worker records its own boot straight to the database, because every other report it makes travels through the queue",
    file: "apps/worker/src/jobs/diagnostics.ts",
    from: '    state: boot ? (bootDetail.queueReachable === false ? "blocked" : "ok") : "unknown",',
    to: '    state: "ok",',
    pkg: "@le/worker",
  },
  {
    id: "health/an-unreachable-queue-is-named-as-one",
    rule: "A worker that is up but cannot reach its queue is reported as that, not as a worker that is down",
    file: "apps/web/src/lib/pacing.ts",
    from: "  if (boot && detail.queueReachable === false) {",
    to: "  if (false) {",
    pkg: "@le/web",
  },
  {
    id: "health/a-production-worker-must-have-a-real-queue",
    rule: "A production worker pointed at its own localhost is refused at boot, not discovered at the first campaign",
    file: "apps/worker/src/config.ts",
    from: "  if (isProduction(env.NODE_ENV) && isLocalRedis(env.REDIS_URL)) {",
    to: "  if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "health/the-health-check-looks-at-the-queue",
    rule: "A worker that cannot reach its queue reports itself unhealthy, rather than Live with nothing being consumed",
    file: "apps/worker/src/server.ts",
    from: "    const queue = await queueReachable(connection);",
    to: "    const queue = true;",
    pkg: "@le/worker",
  },
  {
    id: "health/work-is-refused-when-it-cannot-be-queued",
    rule: "A job the queue cannot hold is refused, not answered with \"queued\"",
    file: "apps/worker/src/server.ts",
    from: "    if (connection && !(await queueReachable(connection))) {",
    to: "    if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "health/a-queue-that-never-answers-is-not-healthy",
    rule: "The reachability check has a deadline; a client that retries for ever makes an unbounded wait indistinguishable from an answer",
    file: "apps/worker/src/queues.ts",
    from: "    return (await Promise.race([pong, deadline])) === \"PONG\";",
    to: "    return (await pong) === \"PONG\";",
    pkg: "@le/worker",
  },
  {
    id: "pacing/launching-is-a-round-trip",
    rule: "Launching asks the worker to start, so a worker that is not there is found out at the press rather than never",
    file: "apps/worker/src/server.ts",
    from: '  app.post("/jobs/campaign-tick", async (c) => {\n    const parsed = CampaignTickRequest.safeParse(await c.req.json().catch(() => null));\n    if (!parsed.success) return c.json({ error: "invalid request" }, 400);\n    if (!(await assertMembership(ctx.db, parsed.data.workspaceId, parsed.data.userId))) {',
    to: '  app.post("/jobs/campaign-tick", async (c) => {\n    const parsed = CampaignTickRequest.safeParse(await c.req.json().catch(() => null));\n    if (!parsed.success) return c.json({ error: "invalid request" }, 400);\n    if (false) {',
    pkg: "@le/worker",
  },
  {
    id: "pacing/a-run-that-sent-nobody-still-says-it-ran",
    rule: "The sending loop records every run, so its silence can be told from its absence",
    file: "apps/worker/src/jobs/campaign-tick.ts",
    from: "  await beat(db, now, { campaigns: campaigns.length, enqueued });",
    to: "  if (enqueued > 0) await beat(db, now, { campaigns: campaigns.length, enqueued });",
    pkg: "@le/worker",
  },
  {
    id: "pacing/a-dead-loop-is-reported-before-anything-else",
    rule: "A worker that is not running outranks every gentler explanation for silence",
    file: "apps/web/src/lib/pacing.ts",
    from: "  if (beat === null || now.getTime() - beat > PACING_STALE_MS) {",
    to: "  if (false) {",
    pkg: "@le/web",
  },
  {
    id: "pacing/a-launched-campaign-says-what-it-is-doing",
    rule: "A running campaign that has sent nothing explains itself rather than looking broken",
    file: "apps/web/src/lib/pacing.ts",
    from: '  if (input.status !== "running") return null;',
    to: "  return null;",
    pkg: "@le/web",
  },
  {
    id: "diagnostics/the-sending-loop-is-checked",
    rule: "The system check asks whether the loop that sends is alive; every other green tick is meaningless without it",
    file: "apps/worker/src/jobs/diagnostics.ts",
    from: '    state: beating ? "ok" : "blocked",',
    to: '    state: "ok",',
    pkg: "@le/worker",
  },
  {
    id: "targeting/position-moves-on",
    rule: "A page that yielded nobody new is still a page the search has passed",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "  if (continuing) await rememberPosition(ctx, job, continuing.id, page.cursor);",
    to: "  /* mutated */",
    pkg: "@le/worker",
  },
  {
    id: "targeting/campaign-owns-its-profile",
    rule: "A continuation searches the campaign's own customer profile, not the request's",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "  const customerProfileId = continuing?.customer_profile_id ?? job.customerProfileId;",
    to: "  const customerProfileId = job.customerProfileId;",
    pkg: "@le/worker",
  },
  {
    id: "targeting/exhausted-search-stops",
    rule: "A search LinkedIn has read to the end is not run again",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "    if (row.search_exhausted) {",
    to: "    if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "search/position-is-handed-back",
    rule: "A classic search reports where it stopped, so the next run can continue it",
    file: "packages/linkedin/src/unipile.ts",
    from: "      position = nextPosition(round, next, terms, withIndustry);",
    to: "      position = null;",
    pkg: "@le/linkedin",
  },
  {
    id: "search/resumes-each-term",
    rule: "A resumed search asks each term from where it stopped",
    file: "packages/linkedin/src/unipile.ts",
    from: "        if (at) params.set(\"cursor\", at);",
    to: "        /* mutated */",
    pkg: "@le/linkedin",
  },
  {
    id: "search/exhausted-term-leaves",
    rule: "A term with no more pages is dropped rather than restarted from the top",
    file: "packages/linkedin/src/unipile.ts",
    from: "        if (res.cursor) next[term] = res.cursor;\n        else delete next[term];",
    to: "        next[term] = res.cursor ?? \"\";",
    pkg: "@le/linkedin",
  },
  {
    id: "search/unasked-term-keeps-its-place",
    rule: "A term this run had no room for is not stepped over",
    file: "packages/linkedin/src/unipile.ts",
    from: "      const next: Record<string, string> = { ...start };",
    to: "      const next: Record<string, string> = {};",
    pkg: "@le/linkedin",
  },
  {
    id: "search/industry-pass-is-not-the-end",
    rule: "Running out inside the industry filter is not running out of people",
    file: "packages/linkedin/src/unipile.ts",
    from: "  if (withIndustry) return { round: round + 1, terms: Object.fromEntries(terms.map((t) => [t, \"\"])) };",
    to: "  /* mutated */",
    pkg: "@le/linkedin",
  },
  {
    id: "search/foreign-cursor-refused",
    rule: "A cursor we did not write is never resumed from",
    file: "packages/linkedin/src/cursor.ts",
    from: "      if (typeof at !== \"string\") return null;",
    to: "      if (typeof at !== \"string\") continue;",
    pkg: "@le/linkedin",
  },
  {
    id: "strategy/needs-input",
    rule: "The Strategy Agent refuses to invent an ICP from nothing",
    file: "packages/agents/src/strategy.ts",
    from: "if (!input.websiteUrl && !input.linkedinCompanyUrl && !input.description && !input.websiteText) {",
    to: "if (false) {",
    pkg: "@le/agents",
  },
  {
    id: "strategy/profiles-unapproved",
    rule: "Generated profiles wait for a human before targeting acts on them",
    file: "apps/worker/src/jobs/strategy.ts",
    from: "      priority: profile.priority,",
    to: "      priority: profile.priority,\n      approved_at: new Date().toISOString(),",
    pkg: "@le/worker",
  },
  {
    id: "crm/html-escaping",
    rule: "Prospect text cannot inject markup into a CRM note",
    file: "packages/crm/src/hubspot.ts",
    from: "return `<b>${who}</b><br><br>${escapeHtml(activity.body).replace(/\\n/g, \"<br>\")}`;",
    to: "return `<b>${who}</b><br><br>${activity.body}`;",
    pkg: "@le/crm",
  },
  {
    id: "connect/binds-the-provider-account",
    rule: "A finished hosted login binds the provider account, or nothing ever sends",
    file: "apps/worker/src/server.ts",
    from: "        provider_account_id: account.providerAccountId,",
    to: "        provider_account_id: null,",
    pkg: "@le/worker",
  },
  {
    id: "connect/no-rebinding",
    rule: "A replayed connection notice never repoints an account already working",
    file: "apps/worker/src/server.ts",
    from: '.in("status", ["connecting", "reauth_required", "restricted"])',
    to: '.not("status", "is", null)',
    pkg: "@le/worker",
  },
  {
    id: "connect/verified-deliveries-only",
    rule: "An unverifiable connection notice binds nothing",
    file: "apps/worker/src/server.ts",
    from: '      console.error("rejected account webhook", err);\n      return c.json({ error: "invalid signature" }, 401);',
    to: '      console.error("rejected account webhook", err);\n      accounts = [];',
    pkg: "@le/worker",
  },
  {
    id: "health/recovers-from-restriction",
    rule: "An account whose restriction lifts starts sending again",
    file: "apps/worker/src/accounts.ts",
    from: 'if (account.status !== "active" && account.status !== "connecting") {',
    to: 'if (account.status === "warning") {',
    pkg: "@le/worker",
  },
  {
    id: "acceptance/notices-a-connection",
    rule: "An accepted invitation is noticed, which is what starts the follow-up sequence",
    file: "apps/worker/src/jobs/acceptance.ts",
    from: "if (!providerId || !connected.has(providerId)) continue;",
    to: "if (true) continue;",
    pkg: "@le/worker",
  },
  {
    id: "acceptance/schedules-the-follow-up",
    rule: "Accepting schedules the first follow-up, not merely a status change",
    file: "apps/worker/src/jobs/acceptance.ts",
    from: "next_action_at: new Date(now.getTime() + delayDays * 86_400_000).toISOString(),",
    to: "next_action_at: null,",
    pkg: "@le/worker",
  },
  {
    id: "acceptance/withdrawn-invitations",
    rule: "A connection made long after a withdrawn invitation is not counted as accepting it",
    file: "apps/worker/src/jobs/acceptance.ts",
    from: '.gte("invited_at", oldest.toISOString())',
    to: '.not("invited_at", "is", null)',
    pkg: "@le/worker",
  },
  {
    id: "limiter/atomic-counters",
    rule: "Two sends at once are both counted, so an account cannot slip past its cap",
    file: "apps/worker/src/accounts.ts",
    from: 'const { error } = await db.rpc("record_linkedin_action", { p_account_id: accountId, p_kind: kind });',
    to: [
      'const { data: row } = await db',
      '    .from("linkedin_accounts")',
      '    .select("invites_today, invites_this_week, messages_today")',
      '    .eq("id", accountId)',
      "    .single();",
      "  const error = null;",
      "  if (row) {",
      '    await db.from("linkedin_accounts").update({',
      '      invites_today: kind === "invite" ? row.invites_today + 1 : row.invites_today,',
      '      invites_this_week: kind === "invite" ? row.invites_this_week + 1 : row.invites_this_week,',
      '      messages_today: kind === "message" ? row.messages_today + 1 : row.messages_today,',
      '    }).eq("id", accountId);',
      "  }",
    ].join("\n  "),
    pkg: "@le/worker",
  },
  {
    id: "limiter/uncounted-action",
    rule: "A counter write that fails is raised, never swallowed",
    file: "apps/worker/src/accounts.ts",
    from: "if (error) throw new Error(",
    to: "if (false) throw new Error(",
    pkg: "@le/worker",
  },
  {
    id: "digest/event-subject-types",
    rule: "A digest counts an event against the id space its subject actually lives in",
    file: "apps/worker/src/jobs/digest.ts",
    from: "const owned = mine[event.subject_type];",
    to: "const owned = mine.campaign_prospect;",
    pkg: "@le/worker",
  },
  {
    id: "digest/low-acceptance-warning",
    rule: "The low acceptance warning the nightly sweep records reaches the rep",
    file: "apps/worker/src/jobs/digest.ts",
    from: "  if (lowAcceptance) {",
    to: "  if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "pricing/unpriced-is-not-free",
    rule: "A model we cannot price reports unknown cost, never zero",
    file: "packages/shared/src/pricing.ts",
    from: "if (!price) return null;",
    to: "if (!price) return 0;",
    pkg: "@le/shared",
  },
  {
    id: "pricing/never-rounds-a-cost-to-nothing",
    rule: "A real cost is never displayed as $0.00",
    file: "packages/shared/src/pricing.ts",
    from: "  if (Math.abs(amount) < 0.01) {",
    to: "  if (false) {",
    pkg: "@le/shared",
  },
  {
    id: "usage/partial-total-is-no-total",
    rule: "A spend total containing an unpriced call is reported as unknown",
    file: "apps/web/src/lib/usage.ts",
    from: "if (costUsd !== null) costUsd = row.cost_usd === null ? null : costUsd + row.cost_usd;",
    to: "costUsd = (costUsd ?? 0) + (row.cost_usd ?? 0);",
    pkg: "@le/web",
  },
  {
    id: "knowledge/no-truncation",
    rule: "A document too long for the prompt is left out whole, never trimmed to fit",
    file: "packages/agents/src/knowledge.ts",
    from: "    if (used + cost <= budget) {",
    to: "    if (true) {",
    pkg: "@le/agents",
  },
  {
    id: "knowledge/names-omissions",
    rule: "The agent is told which documents it has not read, so it hands off instead of guessing",
    file: "packages/agents/src/knowledge.ts",
    from: "  if (omitted.length === 0) return body;",
    to: "  return body;",
    pkg: "@le/agents",
  },
  {
    id: "holds/booking-survives-a-reply",
    rule: "Sending a reply never clears a hold asking someone to book a meeting by hand",
    file: "apps/worker/src/holds.ts",
    from: '    .eq("id", conversationId)\n    .eq("needs_human_kind", kind);',
    to: '    .eq("id", conversationId);',
    pkg: "@le/worker",
  },
  {
    id: "holds/undraftable-reply",
    rule: "A reply the agent could not draft is still put in front of a person",
    file: "apps/worker/src/jobs/inbound.ts",
    from: 'await flagForHuman(db, conversation.id, "could not draft a reply, answer this one yourself");',
    to: "// mutated",
    pkg: "@le/worker",
  },
  {
    id: "calendar/feed-cannot-reach-this-network",
    rule: "A calendar feed URL is refused when it points inside this network; the worker holds the service role and answers on localhost",
    file: "packages/calendar/src/feed-url.ts",
    from: "  if (isPrivateHostname(url.hostname)) {",
    to: "  if (false) {",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/feed-must-be-https",
    rule: "A calendar feed address must be https; it is a bearer credential for the rep's whole calendar",
    file: "packages/calendar/src/feed-url.ts",
    from: '  if (url.protocol !== "https:") {',
    to: "  if (false) {",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/a-cancelled-event-is-not-busy",
    rule: "A cancelled or free-marked event in a feed is not busy time, or it blocks a slot the rep really has",
    file: "packages/calendar/src/ics-parse.ts",
    from: '    if (key === "STATUS" && value.toUpperCase() === "CANCELLED") return null;',
    to: "    // mutated: treats a cancelled event as busy",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/recurrence-is-expanded",
    rule: "A recurring event blocks every occurrence, not just the first; a weekly standup counted once is fifty-one wrong slots a year",
    file: "packages/calendar/src/ics-parse.ts",
    from: "  if (!event.rrule) {",
    to: "  if (true) {",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/zoned-times-use-their-own-offset",
    rule: "A feed time with a TZID is resolved through that zone, not read as UTC, or every block lands hours from the meeting",
    file: "packages/calendar/src/ics-parse.ts",
    from: "  return { at: localToUtc(parts, zone), allDay: isDate };",
    to: "  return { at: Date.UTC(parts.year, parts.month - 1, parts.day, parts.hour, parts.minute, parts.second), allDay: isDate };",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/a-feed-is-busy-time",
    rule: "Busy periods read from the rep's own calendar are treated as busy, or the feed is decorative",
    file: "apps/worker/src/calendar.ts",
    from: "      blackouts: [...(blackouts ?? []), ...(feedBusy ?? [])].map(toInterval),",
    to: "      blackouts: (blackouts ?? []).map(toInterval),",
    pkg: "@le/worker",
  },
  {
    id: "calendar/a-failing-feed-keeps-its-last-read",
    rule: "A feed that fails to refresh keeps the intervals from its last good read; deleting them makes a rotated URL look like a free calendar",
    file: "apps/worker/src/jobs/calendar-feed.ts",
    from: "      await markFailing(ctx, feed.id, fetched.error);\n      continue;",
    to: "      await ctx.db.from(\"calendar_feed_busy\").delete().eq(\"feed_id\", feed.id);\n      continue;",
    pkg: "@le/worker",
  },
  {
    id: "calendar/only-a-time-we-offered",
    rule: "A booking only ever takes a time the page actually offered; startsAt from a form is not authority to book",
    file: "apps/worker/src/jobs/book.ts",
    from: "  if (!offer.iso.includes(input.startsAt)) {",
    to: "  if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "calendar/an-expired-link-books-nothing",
    rule: "An expired or revoked booking link cannot be used to book, not merely to view",
    file: "apps/worker/src/jobs/book.ts",
    from: "  if (Date.parse(data.expires_at) < Date.now()) {",
    to: "  if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "calendar/what-we-booked-is-busy",
    rule: "Meetings this product booked are treated as busy, or it offers the same slot twice",
    file: "packages/calendar/src/own.ts",
    from: "    return [...this.state.meetings, ...this.state.blackouts].filter((interval) => {",
    to: "    return [...this.state.blackouts].filter((interval) => {",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/a-blackout-spanning-the-window-still-blocks",
    rule: "A blackout that starts before the window and ends inside it still blocks; containment would offer the time anyway",
    file: "packages/calendar/src/own.ts",
    from: "      return start < to && end > from;",
    to: "      return start >= from && end <= to;",
    pkg: "@le/calendar",
  },
  {
    id: "calendar/ics-escapes-its-values",
    rule: "An invitation escapes commas and newlines, or a company with a comma in its name truncates the meeting title",
    file: "packages/calendar/src/ics.ts",
    from: "    .replace(/,/g, \"\\\\,\")",
    to: "",
    pkg: "@le/calendar",
  },
  {
    id: "system/asks-the-provider-not-the-row",
    rule: "The system check asks the provider whether it still has the account, rather than trusting the stored row",
    file: "apps/worker/src/jobs/diagnostics.ts",
    from: "    const health = await ctx.linkedin.getAccountHealth(providerAccountId);",
    to: '    const health = "ok" as const;',
    pkg: "@le/worker",
  },
  {
    id: "system/never-passes-a-check-it-skipped",
    rule: "A stage the system check could not attempt reports as waiting, never as working",
    file: "apps/worker/src/jobs/diagnostics.ts",
    from: '      state: "waiting",\n      detail: "Not attempted: the account has to be connected and live first.",',
    to: '      state: "ok",\n      detail: "Not attempted: the account has to be connected and live first.",',
    pkg: "@le/worker",
  },
  {
    id: "system/a-missing-webhook-secret-blocks-replies",
    rule: "A deployment with no webhook secret is reported as blocking replies, because it rejects every one of them",
    file: "apps/worker/src/jobs/diagnostics.ts",
    from: '    state: env.UNIPILE_WEBHOOK_SECRET ? "ok" : live ? "blocked" : "waiting",',
    to: '    state: "ok" as const,',
    pkg: "@le/worker",
  },
  {
    id: "strategy/queued-is-visible",
    rule: "Queueing the Strategy Agent is recorded, so the minutes before it answers are not read as the person never having done onboarding",
    file: "apps/worker/src/server.ts",
    from: '      name: "strategy.queued",',
    to: '      name: "strategy.ignored",',
    pkg: "@le/worker",
  },
  {
    id: "strategy/a-failed-run-says-so",
    rule: "A Strategy Agent run that failed is reported as failed, not left looking like one still going",
    file: "apps/web/src/lib/strategy-state.ts",
    from: '  if (data.name === "strategy.failed") {',
    to: "  if (false) {",
    pkg: "@le/web",
  },
  {
    id: "strategy/onboarding-is-done-when-the-person-is-done",
    rule: "The onboarding step ticks when the person has submitted, not when the agent has finished writing",
    file: "apps/web/src/lib/strategy-state.ts",
    from: '  return strategy.phase !== "absent";',
    to: '  return strategy.phase === "ready";',
    pkg: "@le/web",
  },
  {
    id: "strategy/targeting-needs-approval",
    rule: "Targeting refuses a customer profile no human has approved",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "if (!profileRow.approved_at) {",
    to: "if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "strategy/empty-search",
    rule: "A search must have something to match on, or it returns anyone",
    file: "apps/web/src/lib/profile-form.ts",
    from: "    filters.keywords.length === 0",
    to: "    false",
    pkg: "@le/web",
  },
  {
    id: "launch/inactive-account",
    rule: "A campaign never launches from an account that is not connected and healthy",
    file: "apps/web/src/lib/campaign.ts",
    from: 'if (state.accountStatus !== "active") {',
    to: "if (false) {",
    pkg: "@le/web",
  },
  {
    id: "launch/cap-ceiling",
    rule: "A campaign may ask to send slower than the safe ceiling, never faster",
    file: "apps/web/src/lib/campaign.ts",
    from: "if (state.dailyInviteCap > LINKEDIN_LIMITS.invitesPerDayMax) {",
    to: "if (false) {",
    pkg: "@le/web",
  },
  {
    id: "launch/empty-message",
    rule: "A campaign never launches with a blank message in its sequence",
    file: "apps/web/src/lib/campaign.ts",
    from: "const blank = state.steps.findIndex((step) => !step.message.trim());",
    to: "const blank = -1;",
    pkg: "@le/web",
  },
  {
    id: "exclusions/send-time-check",
    rule: "An account added to the exclusion list stops sends already queued against it",
    file: "apps/worker/src/jobs/linkedin-action.ts",
    from: "  if (excluded) {",
    to: "  if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "exclusions/targeting-filter",
    rule: "An excluded account never reaches the scoring model or a new campaign",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "(c) => !matchExclusion(exclusions, { company: c.company, linkedinUrl: c.linkedinUrl }),",
    to: "() => true,",
    pkg: "@le/worker",
  },
  {
    id: "exclusions/company-normalization",
    rule: "One company written several ways is one account to the exclusion list",
    file: "packages/shared/src/exclusions.ts",
    from: 'return kind === "person" ? normalizeLinkedInUrl(raw) : normalizeCompany(raw);',
    to: "return raw;",
    pkg: "@le/shared",
  },
  {
    id: "funnel/cumulative-stages",
    rule: "A funnel stage counts everyone who passed it, not only those sitting on it",
    file: "packages/shared/src/funnel.ts",
    from: '{ key: "accepted", label: "Accepted", statuses: AT_LEAST_ACCEPTED },',
    to: '{ key: "accepted", label: "Accepted", statuses: ["accepted"] },',
    pkg: "@le/shared",
  },
  {
    id: "funnel/counts-what-happened",
    rule: "A stage that happened stays counted after a terminal status overwrites it",
    file: "packages/shared/src/funnel.ts",
    from: "const invited = accepted || (row.invited_at || at(\"invited\") ? 1 : 0);",
    to: 'const invited = accepted || (at("invited") ? 1 : 0);',
    pkg: "@le/shared",
  },
  {
    id: "funnel/monotonic",
    rule: "Reaching a later stage implies every earlier one, whatever the row says",
    file: "packages/shared/src/funnel.ts",
    from: "const accepted = replied || (row.accepted_at || at(\"accepted\") ? 1 : 0);",
    to: 'const accepted = row.accepted_at || at("accepted") ? 1 : 0;',
    pkg: "@le/shared",
  },
  {
    id: "funnel/min-sample",
    rule: "A rate is withheld until there is enough of a sample to mean anything",
    file: "packages/shared/src/funnel.ts",
    from: "counts.invited >= MIN_FOR_RATE ? counts.accepted / counts.invited : null",
    to: "counts.accepted / counts.invited",
    pkg: "@le/shared",
  },
  {
    id: "lifecycle/nudge-once",
    rule: "A step is nudged once and never again — repetition is what makes a reminder spam",
    file: "apps/worker/src/jobs/lifecycle.ts",
    from: "const eventName = `onboarding.nudged.${step.key}`;",
    to: "const eventName = `onboarding.nudged.${step.key}.${Math.random()}`;",
    pkg: "@le/worker",
  },
  {
    id: "lifecycle/grace-days",
    rule: "Nobody is nudged in their first days — someone who signed up an hour ago is reading, not stalled",
    file: "apps/worker/src/jobs/lifecycle.ts",
    from: "if (daysIn < GRACE_DAYS) return 0;",
    to: "if (false) return 0;",
    pkg: "@le/worker",
  },
  {
    id: "lifecycle/no-trial-dunning",
    rule: "A workspace that has already subscribed is never warned that its trial is ending",
    file: "apps/worker/src/jobs/lifecycle.ts",
    from: 'if (workspace.subscription_status === "active" || !workspace.trial_ends_at) return 0;',
    to: "if (false) return 0;",
    pkg: "@le/worker",
  },
  {
    id: "onboarding/welcome-once",
    rule: "The welcome email is sent once per workspace, however often strategy is re-run",
    file: "apps/worker/src/jobs/strategy.ts",
    from: "if (already) return;",
    to: "if (false) return;",
    pkg: "@le/worker",
  },
  {
    id: "booking/first-meeting-only",
    rule: "The meeting email announces the first booking only, never every one",
    file: "apps/worker/src/jobs/booking.ts",
    from: "if ((count ?? 0) !== 1) return;",
    to: "if (false) return;",
    pkg: "@le/worker",
  },
  {
    id: "llm/cached-tokens-not-double-counted",
    rule: "A cached token is billed once — OpenAI counts it inside input_tokens, the cost model does not",
    file: "packages/agents/src/llm.ts",
    from: "inputTokens: Math.max(0, inputTokens - cacheReadTokens),",
    to: "inputTokens,",
    pkg: "@le/agents",
  },
  {
    id: "llm/provider-never-falls-back",
    rule: "A named provider whose key is missing fails, rather than silently running on the other one",
    file: "packages/agents/src/llm.ts",
    from: 'if (!env.OPENAI_API_KEY) throw new Error("LLM_PROVIDER=openai but OPENAI_API_KEY is not set");',
    to: "if (!env.OPENAI_API_KEY) return new AnthropicClient({ apiKey: env.ANTHROPIC_API_KEY });",
    pkg: "@le/agents",
  },
  {
    id: "llm/a-truncated-answer-is-retried-with-room",
    rule: "A model that spent its budget thinking is retried with more room and less effort; a live campaign died because that read as an unparsable answer",
    file: "packages/agents/src/client.ts",
    from: '      if (response.incomplete === "max_tokens") throw new TruncatedOutputError(call.agent);',
    to: "      // mutated: reports it as unparsable",
    pkg: "@le/agents",
  },
  {
    id: "llm/only-truncation-is-retried",
    rule: "A refusal or a model ignoring its schema is never retried; both need a different prompt, not a bigger budget",
    file: "packages/agents/src/client.ts",
    from: "    if (!(error instanceof TruncatedOutputError)) throw error;",
    to: "    if (false) throw error;",
    pkg: "@le/agents",
  },
  {
    id: "llm/refusal-is-not-an-answer",
    rule: "A refusal is surfaced, never returned as prose a prospect could receive",
    file: "packages/agents/src/llm.ts",
    from: "refusal: findRefusal(response),",
    to: "refusal: null,",
    pkg: "@le/agents",
  },
  {
    id: "search/tier-follows-the-account",
    rule: "The search tier follows the account's actual subscription, not an assumption that everyone pays for Sales Navigator",
    file: "apps/worker/src/jobs/targeting.ts",
    from: 'const searchTier = account.has_sales_navigator ? "sales_navigator" : "classic";',
    to: 'const searchTier = "sales_navigator";',
    pkg: "@le/worker",
  },
  {
    id: "connect/a-job-that-learns-the-account-is-gone-says-so",
    rule: "A job told the provider has no such account marks the row, rather than leaving the Team page claiming it is connected until the nightly poll",
    file: "apps/worker/src/jobs/targeting.ts",
    from: "      await markAccountGone(db, { id: account.id, workspace_id: job.workspaceId });",
    to: "      // mutated: leaves the row claiming to be connected",
    pkg: "@le/worker",
  },
  {
    id: "connect/only-account-errors-disconnect",
    rule: "Only a provider failure that is actually about the account disconnects it; an outage does not make a rep re-do the hosted login",
    file: "packages/linkedin/src/unipile.ts",
    from: "  return /account not found/i.test(err.body);",
    to: "  return true;",
    pkg: "@le/linkedin",
  },
  {
    id: "connect/an-unlabelled-account-is-not-a-missing-one",
    rule: "An account whose id the provider still holds is never torn down for carrying somebody else's label; existence and ownership are different questions",
    file: "apps/worker/src/accounts.ts",
    from: "    if (all.some((a) => a.providerAccountId === row.provider_account_id)) {",
    to: "    if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "connect/a-dead-account-stops-claiming-to-work",
    rule: "A row holding an account the provider no longer has stops saying it is connected, so the rep can reconnect it",
    file: "apps/worker/src/accounts.ts",
    from: '        status: "reauth_required",\n        status_detail:\n          "LinkedIn\'s provider no longer has this account. Reconnect it to start sending again.",',
    to: '        status_detail: null,',
    pkg: "@le/worker",
  },
  {
    id: "connect/a-dead-account-offers-a-way-back",
    rule: "An account that cannot send shows a way to connect again; the Reconnect banner must not lead to a page with nothing to press",
    file: "apps/web/src/app/app/team/repair.ts",
    from: '  return !["active", "warning", "restricted"].includes(status);',
    to: '  return status === "connecting";',
    pkg: "@le/web",
  },
  {
    id: "connect/a-paused-account-is-not-a-disconnected-one",
    rule: "A LinkedIn restriction is not offered a reconnect; signing in again does not lift one and hides the real reason",
    file: "apps/web/src/app/app/team/repair.ts",
    from: '  return !["active", "warning", "restricted"].includes(status);',
    to: '  return status !== "active";',
    pkg: "@le/web",
  },
  {
    id: "connect/an-unlabelled-account-is-never-claimed",
    rule: "An account the provider has not labelled with this rep is explained, never attached; one labelled with nobody could belong to anybody",
    file: "apps/web/src/app/app/team/repair.ts",
    from: "  if (found > 0 && (data?.mine ?? 0) === 0) {",
    to: "  if (false) {",
    pkg: "@le/web",
  },
  {
    id: "connect/the-repair-says-what-it-found",
    rule: "The automatic repair renders what the provider told it; repairing silently and failing silently are the same page",
    file: "apps/web/src/app/app/team/repair.ts",
    from: "  if (!result.ok) {",
    to: "  if (false) {",
    pkg: "@le/web",
  },
  {
    id: "connect/a-broken-account-repairs-itself",
    rule: "An account the provider has replaced is repaired without anyone pressing a button; recovery behind a button is permanent for whoever does not find it",
    file: "apps/worker/src/accounts.ts",
    from: "    const result = await reconcileAccount(db, row.workspace_id, row.user_id, mine, accounts);",
    to: "    const result = { changed: false };",
    pkg: "@le/worker",
  },
  {
    id: "connect/recovery-respects-the-reference",
    rule: "Recovery only ever considers accounts carrying that rep's own user id; otherwise it attaches a stranger's LinkedIn",
    file: "apps/worker/src/accounts.ts",
    from: "    const mine = accounts.filter((a) => a.reference === row.user_id);",
    to: "    const mine = accounts;",
    pkg: "@le/worker",
  },
  {
    id: "connect/an-empty-provider-list-changes-nothing",
    rule: "Recovery finding no account for a rep leaves the row and its reason untouched; a provider outage must not rewrite every account's explanation",
    file: "apps/worker/src/accounts.ts",
    from: "    if (mine.length === 0) continue;",
    to: "    if (false) continue;",
    pkg: "@le/worker",
  },
  {
    id: "connect/asking-repoints-a-stale-id",
    rule: "Asking the provider re-points a live row whose account id has changed; otherwise there is no way back from a dead id",
    file: "apps/worker/src/accounts.ts",
    from: "  const changed = account.providerAccountId !== row.provider_account_id;",
    to: "  const changed = false;",
    pkg: "@le/worker",
  },
  {
    id: "connect/reconcile-respects-the-reference",
    rule: "Reconciling only ever considers accounts carrying this rep's own user id as their reference",
    file: "apps/worker/src/server.ts",
    from: "    const reconciled = await reconcileAccount(ctx.db, parsed.data.workspaceId, parsed.data.userId, mine, accounts);",
    to: "    const reconciled = await reconcileAccount(ctx.db, parsed.data.workspaceId, parsed.data.userId, accounts, accounts);",
    pkg: "@le/worker",
  },
  {
    id: "search/provider-says-why",
    rule: "A provider failure carries the provider's own sentence, not only its status code",
    file: "packages/linkedin/src/unipile.ts",
    from: '        `Unipile ${init.method ?? "GET"} ${path} failed with ${res.status}${said(text)}`,',
    to: '        `Unipile ${init.method ?? "GET"} ${path} failed with ${res.status}`,',
    pkg: "@le/linkedin",
  },
  {
    id: "search/failed-lookup-is-not-an-absent-term",
    rule: "A taxonomy lookup that could not be made is reported as that, never as LinkedIn not having the term",
    file: "packages/linkedin/src/unipile.ts",
    from: "        if (looked.failed) {",
    to: "        if (false) {",
    pkg: "@le/linkedin",
  },
  {
    id: "search/a-placeholder-is-not-a-name",
    rule: "LinkedIn's \"LinkedIn Member\" placeholder is never stored as somebody's name",
    file: "packages/linkedin/src/unipile.ts",
    from: "  if (!whole || /^linkedin member$/i.test(whole)) return { firstName: \"\", lastName: \"\" };",
    to: '  if (!whole) return { firstName: "", lastName: "" };',
    pkg: "@le/linkedin",
  },
  {
    id: "search/an-internal-id-is-not-a-slug",
    rule: "A public_identifier that is really an internal id never becomes a profile address; it is present on every hidden profile and 404s",
    file: "packages/linkedin/src/unipile.ts",
    from: "  if (raw.public_identifier && !isInternalId(raw.public_identifier)) {",
    to: "  if (raw.public_identifier) {",
    pkg: "@le/linkedin",
  },
  {
    id: "search/second-degree-only",
    rule: "Classic search asks for second-degree connections only; third-degree profiles have no name and no address for a reviewer to check",
    file: "packages/linkedin/src/unipile.ts",
    from: "              network_distance: [2],",
    to: "              network_distance: [1, 2, 3],",
    pkg: "@le/linkedin",
  },
  {
    id: "search/a-prospect-has-a-name",
    rule: "A prospect's name is read from whichever field carries it; a blank name makes a real list look invented",
    file: "packages/linkedin/src/unipile.ts",
    from: "  const whole = (raw.name ?? \"\").trim().replace(/\\s+/g, \" \");",
    to: '  const whole = "";',
    pkg: "@le/linkedin",
  },
  {
    id: "search/a-fabricated-url-is-never-a-link",
    rule: "A URL whose slug is the provider id is never rendered as a link, however much it looks like a profile address",
    file: "packages/shared/src/exclusions.ts",
    from: "  if (providerId && slug.toLowerCase() === providerId.toLowerCase()) return false;",
    to: "  if (false) return false;",
    pkg: "@le/shared",
  },
  {
    id: "search/a-provider-id-slug-is-never-a-link",
    rule: "A LinkedIn internal id in a profile slug is rejected even when the provider id was not kept, because legacy rows hold exactly that",
    file: "packages/shared/src/exclusions.ts",
    from: "  return !/^acoaa/i.test(slug);",
    to: "  return true;",
    pkg: "@le/shared",
  },
  {
    id: "search/never-fabricate-a-profile-url",
    rule: "A provider id is never pasted into a profile URL; every one of those links is a 404 and a reviewer concludes the list is fake",
    file: "packages/linkedin/src/unipile.ts",
    from: "  return `https://www.linkedin.com/search/results/all/?keywords=${encodeURIComponent(identifier)}`;",
    to: "  return `https://www.linkedin.com/in/${identifier}`;",
    pkg: "@le/linkedin",
  },
  {
    id: "search/one-keyword-at-a-time",
    rule: "Classic search is asked one plain term per request; its keyword box is not a query language and a boolean string matches nobody",
    file: "packages/linkedin/src/unipile.ts",
    from: "              keywords: term,",
    to: "              keywords: terms.join(\" OR \"),",
    pkg: "@le/linkedin",
  },
  {
    id: "search/widening-is-reported",
    rule: "A list broader than the profile asked for says so; a reviewer told it is what they approved cannot check it",
    file: "packages/linkedin/src/unipile.ts",
    from: "            \"Nobody matched inside those industries, so the industry filter was dropped. Read the names carefully — this list is not filtered by industry at all.\",",
    to: "            \"\",",
    pkg: "@le/linkedin",
  },
  {
    id: "search/widening-never-leaves-the-location",
    rule: "Widening never gives up the location; a campaign quietly messaging another continent is worse than one that finds nobody",
    file: "packages/linkedin/src/unipile.ts",
    from: "              ...(resolved.locations.length ? { location: resolved.locations } : {}),",
    to: "              ...(withIndustry && resolved.locations.length ? { location: resolved.locations } : {}),",
    pkg: "@le/linkedin",
  },
  {
    id: "search/filters-are-ids-not-names",
    rule: "Locations and industries are searched by LinkedIn's id; sending the words returns nobody",
    file: "packages/linkedin/src/unipile.ts",
    from: "              ...(withIndustry ? { industry: resolved.industries } : {}),",
    to: "              ...(withIndustry ? { industry: input.query.industries } : {}),",
    pkg: "@le/linkedin",
  },
  {
    id: "search/unmatched-terms-are-named",
    rule: "A term LinkedIn's taxonomy does not have is reported, not quietly left out of the search",
    file: "packages/linkedin/src/unipile.ts",
    from: '          notes.push(`LinkedIn has no ${field} called "${name}", so it was left out of the search.`);',
    to: "          // mutated: says nothing",
    pkg: "@le/linkedin",
  },
  {
    id: "search/terms-are-alternatives",
    rule: "Several titles or keywords are searched one at a time; joined into one box they are an AND that matches nobody",
    file: "packages/linkedin/src/unipile.ts",
    from: '  return unique.length > 0 ? unique.slice(0, 6) : [""];',
    to: '  return unique.length > 0 ? [unique.join(" ")] : [""];',
    pkg: "@le/linkedin",
  },
  {
    id: "search/dropped-filters-are-named",
    rule: "A filter classic search cannot apply is reported, never silently dropped from the list a human approves",
    file: "packages/linkedin/src/unipile.ts",
    from: 'if (query.seniorities?.length) droppedFilters.push("seniority");',
    to: "if (false) droppedFilters.push('seniority');",
    pkg: "@le/linkedin",
  },
  {
    id: "search/classic-is-the-default",
    rule: "An unspecified tier means classic — assuming a paid seat fails silently and returns nothing",
    file: "packages/linkedin/src/unipile.ts",
    from: 'const tier = input.tier ?? "classic";',
    to: 'const tier = input.tier ?? "sales_navigator";',
    pkg: "@le/linkedin",
  },
  {
    id: "config/base-urls-have-no-trailing-slash",
    rule: "A base URL with a trailing slash does not produce a // route",
    file: "apps/worker/src/config.ts",
    from: '  return value.replace(/\\/+$/, "");',
    to: "  return value;",
    pkg: "@le/worker",
  },
  {
    id: "config/dsn-must-be-a-url",
    rule: "A DSN that is not a URL is refused at boot, not at the first send",
    file: "apps/worker/src/config.ts",
    from: "    .refine(isAbsoluteHttpUrl, {",
    to: "    .refine(() => true, {",
    pkg: "@le/worker",
  },
  {
    id: "config/unipile-required-when-live",
    rule: "A worker that will really reach LinkedIn refuses to boot without Unipile credentials, rather than failing at the first send",
    file: "apps/worker/src/config.ts",
    from: 'if (env.LINKEDIN_PROVIDER === "unipile") {',
    to: "if (false) {",
    pkg: "@le/worker",
  },
  {
    id: "limiter/warmup-starts-at-first-send",
    rule: "The warm-up ramp starts at an account's first action, so one connected weeks early still starts at the low cap",
    file: "packages/linkedin/src/rate-limit.ts",
    from: "if (!firstActionAt) return invitesPerDayStart;",
    to: "if (!firstActionAt) return invitesPerDayMax;",
    pkg: "@le/linkedin",
  },
];

const filter = process.argv[2];
const selected = filter ? MUTATIONS.filter((m) => m.id.includes(filter)) : MUTATIONS;

if (selected.length === 0) {
  console.error(`No mutations match "${filter}"`);
  process.exit(2);
}

console.log(`Running ${selected.length} mutations\n`);

const survived = [];
const inapplicable = [];

for (const mutation of selected) {
  const original = readFileSync(mutation.file, "utf8");

  if (!original.includes(mutation.from)) {
    // The code moved and the mutation no longer describes it. That is a
    // failure of this file, not of the tests, and it must be loud: a stale
    // mutation silently stops checking anything.
    inapplicable.push(mutation);
    console.log(`  STALE     ${mutation.id} — target text not found in ${mutation.file}`);
    continue;
  }

  writeFileSync(mutation.file, original.replace(mutation.from, mutation.to));

  let caught = false;
  try {
    execSync(`pnpm --filter ${mutation.pkg} test`, { stdio: "pipe" });
  } catch {
    // A non-zero exit means a test failed, which is what we want.
    caught = true;
  } finally {
    writeFileSync(mutation.file, original);
  }

  if (caught) {
    console.log(`  caught    ${mutation.id}`);
  } else {
    survived.push(mutation);
    console.log(`  SURVIVED  ${mutation.id} — ${mutation.rule}`);
  }
}

console.log(`\n${selected.length - survived.length - inapplicable.length}/${selected.length} caught`);

if (survived.length) {
  console.log("\nUnguarded rules — a test should fail when each of these breaks:");
  for (const mutation of survived) console.log(`  ${mutation.id}: ${mutation.rule}`);
}
if (inapplicable.length) {
  console.log("\nStale mutations — update scripts/mutation-check.mjs to match the code:");
  for (const mutation of inapplicable) console.log(`  ${mutation.id} (${mutation.file})`);
}

process.exit(survived.length + inapplicable.length > 0 ? 1 : 0);
