#!/usr/bin/env node
/**
 * Emits the whole schema as one script, installed into a named Postgres schema
 * rather than `public`.
 *
 * The migrations are written unqualified so a fresh Supabase project can run
 * them as they are. This deployment shares a project with an unrelated product
 * whose tables are also called `memberships`, `conversations` and `messages`,
 * so ours live in their own schema and the two never see each other.
 *
 * A schema is not a namespace you can bolt on afterwards. Three things have to
 * change with it, and each is silent when it does not:
 *
 *   1. `security definer` functions pin `search_path` on purpose — a definer
 *      function that resolves its tables through the caller's path is the
 *      classic privilege-escalation hole. Pinning it to `public` here would
 *      make every policy read the other product's `memberships` table.
 *   2. `handle_new_user` writes to `public.profiles` by name.
 *   3. A new schema has none of the grants Supabase gives `public`, so
 *      PostgREST would answer 404 to every request against it. RLS is what
 *      protects the rows; the grants are what make the schema visible at all.
 *
 *   node scripts/schema-install.mjs            # to stdout, schema "le"
 *   node scripts/schema-install.mjs --schema x
 */
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const migrationsDir = join(root, "packages/db/supabase/migrations");

const schemaArg = process.argv.indexOf("--schema");
const schema = schemaArg === -1 ? "le" : process.argv[schemaArg + 1];
if (!/^[a-z_][a-z0-9_]*$/.test(schema)) {
  console.error(`refusing to install into ${schema}: expected a plain lower-case identifier`);
  process.exit(1);
}

const files = readdirSync(migrationsDir).filter((f) => f.endsWith(".sql")).sort();
if (!files.length) {
  console.error(`no migrations found in ${migrationsDir}`);
  process.exit(1);
}

const parts = [
  `-- Generated by scripts/schema-install.mjs — do not edit by hand.`,
  `-- Source: ${files.join(", ")}`,
  ``,
  // citext is used for slugs and email addresses; pgcrypto for gen_random_uuid
  // on projects older than PG13. Both go where Supabase keeps extensions, never
  // in our schema — an extension in a tenant schema cannot be shared.
  `create extension if not exists "pgcrypto" with schema extensions;`,
  `create extension if not exists "citext" with schema extensions;`,
  ``,
  `create schema if not exists ${schema};`,
  ``,
  // Everything unqualified below lands here. `extensions` is on the path for
  // citext; `public` is last so a name we define always wins over the other
  // product's table of the same name.
  `set search_path = ${schema}, extensions, public;`,
  ``,
];

for (const file of files) {
  let sql = readFileSync(join(migrationsDir, file), "utf8");

  // Handled above, in the schema Supabase expects them in.
  sql = sql.replace(/^create extension[^;]+;\s*$/gim, "");

  // The three places a schema name is written down rather than resolved.
  sql = sql.replace(/set search_path = public\b/g, `set search_path = ${schema}`);
  sql = sql.replace(/\bpublic\.(profiles|memberships|workspaces)\b/g, `${schema}.$1`);

  // Triggers on auth.users are global to the project: two products installing
  // "on_auth_user_created" is a collision no schema separates.
  sql = sql.replace(/\bon_auth_user_created\b/g, `on_auth_user_created_${schema}`);

  parts.push(`-- ${"-".repeat(60)} ${file}`, sql.trim(), "");
}

parts.push(
  `-- ${"-".repeat(60)} grants`,
  ``,
  `-- Without these PostgREST answers 404 for every table in the schema, which`,
  `-- reads exactly like a failed migration. RLS still decides which rows each`,
  `-- caller sees; these only make the schema addressable.`,
  `grant usage on schema ${schema} to anon, authenticated, service_role;`,
  `grant all on all tables in schema ${schema} to anon, authenticated, service_role;`,
  `grant all on all sequences in schema ${schema} to anon, authenticated, service_role;`,
  `grant all on all functions in schema ${schema} to anon, authenticated, service_role;`,
  `alter default privileges in schema ${schema} grant all on tables to anon, authenticated, service_role;`,
  `alter default privileges in schema ${schema} grant all on sequences to anon, authenticated, service_role;`,
  `alter default privileges in schema ${schema} grant all on functions to anon, authenticated, service_role;`,
  ``,
  ``,
  `-- Least privilege, applied after the blanket grants above. \`all\` is what`,
  `-- makes the schema addressable; it is not what anon needs. An`,
  `-- unauthenticated request carries the publishable key out of the browser`,
  `-- bundle, and \`grant all\` handed it INSERT, UPDATE, DELETE and TRUNCATE on`,
  `-- every table — platform_admins and messages included. RLS refuses all of it`,
  `-- today, and that is the entire defence: one table added without \`enable row`,
  `-- level security\` and the grant is what makes the omission fatal rather than`,
  `-- merely wrong. anon keeps SELECT, which RLS already denies.`,
  `revoke insert, update, delete, truncate, references, trigger on all tables in schema ${schema} from anon;`,
  `alter default privileges in schema ${schema} revoke insert, update, delete, truncate, references, trigger on tables from anon;`,
  ``,
  `-- record_linkedin_action stays service-role only: the web tier has no`,
  `-- business moving the counters the rate limiter reads, and anything that can`,
  `-- move them can stop an account sending or start its warm-up ramp early.`,
  `revoke execute on function ${schema}.record_linkedin_action(uuid, text) from public, anon, authenticated;`,
  ``,
  `-- Trigger functions are called by their triggers, never over HTTP.`,
  `revoke execute on function ${schema}.handle_new_user() from public, anon, authenticated;`,
  `revoke execute on function ${schema}.touch_updated_at() from public, anon, authenticated;`,
  ``,
  `-- Every RPC this product exposes is called by a signed-in user. PUBLIC is`,
  `-- where CREATE FUNCTION puts EXECUTE by default, and PUBLIC includes anon,`,
  `-- so revoking anon alone leaves the privilege in place.`,
  `revoke execute on function ${schema}.create_workspace(text, text, text) from anon;`,
  `revoke execute on function ${schema}.platform_workspace_stats() from anon;`,
  `revoke execute on function ${schema}.platform_workspace_spend() from anon;`,
  `revoke execute on function ${schema}.is_platform_admin() from public;`,
  `revoke execute on function ${schema}.answer_support_ticket(uuid, text, text) from public;`,
  `alter default privileges in schema ${schema} revoke execute on functions from anon;`,
  ``,
  `-- current_workspace_ids() and is_workspace_admin() deliberately keep EXECUTE`,
  `-- for both roles: every policy here is \`to public\` and resolves through them,`,
  `-- and a policy expression runs with the caller's own privileges. Revoke them`,
  `-- and every table answers with a permission error instead of an empty result.`,
  ``,
);

process.stdout.write(parts.join("\n"));
